const express = require("express");
const router = express.Router();
const admincontreller = require("../controller/admincontroller");
const adminauth = require("../middleware/adminauth");
const { upload } = require("../utils/multer");

router.get("/login", adminauth.islogin, admincontreller.loadlogin);
router.post("/login", admincontreller.login);
router.use(adminauth.checksession);
router.get("/dashboard", admincontreller.loaddashboard);
router.get("/dashboard/chart-data", admincontreller.getChartData);
router.get("/users", admincontreller.loaduser);
router.post("/ban-user", admincontreller.banUser);
router.get("/products", admincontreller.loadProducts);
router.get("/addproduct", admincontreller.loadaddproduct);
router.post("/addproduct", upload, admincontreller.addProduct);
router.post("/products", admincontreller.Productlisting);
router.get("/updateproduct/:id", admincontreller.loadupdateProduct);
router.post("/updateproduct/:id", admincontreller.updateProduct);
router.get("/category", admincontreller.loadcategory);
router.get("/addcategory", admincontreller.loadaddcategory);
router.post("/addcategory", admincontreller.addcategory);
router.get("/categories/update/:id", admincontreller.loadUpdateCategory);
router.post("/categories/update/:id", admincontreller.updateCategory);
router.post("/categories/listing", admincontreller.Categorylisting);
router.get("/order", admincontreller.loadorders);
router.put("/api/orders/:orderId/product-status",admincontreller.updateorderstatus);
router.get("/vieworderdetils", admincontreller.loadviewoderdeatils);
router.get("/coupon", admincontreller.loadcoupon);
router.get("/addcoupon", admincontreller.loadaddcoupon);
router.post("/coupons", admincontreller.addcoupon);
router.get("/updatecoupon/:id", admincontreller.loadupdatecoupon);
router.put("/coupons/:id", admincontreller.updatecoupon);
router.patch("/toggle-coupon/:id", admincontreller.couponstatus);
router.get("/salesreport", admincontreller.loadsalesreport);
router.get("/salesreport/export/pdf", admincontreller.exportSalesPDF);
router.get("/salesreport/export/excel", admincontreller.exportSalesExcel);
router.get("/return", admincontreller.loadreturn);
router.put("/:returnId/status", admincontreller.updateReturnStatus);
router.get("/logout", admincontreller.logout);

module.exports = router;
